version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_PASS=kn
      - RABBITMQ_DEFAULT_USER=kn
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"


  rabbitmq-publisher:
    container_name: 'rabbitmq-publisher'
    build:
      context: ./docker/rabbitmq-publisher
      dockerfile: Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      PUBLISH_FREQUENCY: 5

  db:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass-postgres
      POSTGRES_DB: container-db
    ports:
      - "5432:5432"

  backend:
    container_name: 'backend'
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/container-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=kn
      - SPRING_RABBITMQ_PASSWORD=kn
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
      - rabbitmq-publisher

